  flutter_bloc: ^6.0.5
  equatable: ^1.2.5
  get_it: ^5.0.0
  flutter_platform_widgets: ^0.72.0
  permission_handler: ^5.0.1+1
  image_picker: ^0.6.7+14
  cupertino_icons: ^1.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.1
  intl_translation: ^0.17.10+1
  test: ^1.15.6
  sqflite: ^1.3.2+1
  shared_preferences: ^0.5.12+4
  fluttertoast: ^7.1.1
